# Site settings
title: Wichitalks
email: wichitalks@gmail.com
description: No Pitches. Only Passion.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: wichitalks
github_username: wichitalks

# Build settings
markdown: kramdown