# Site settings
title: Wichitalks
description: An eclectic and insightful series of lightning talks with a twist.
slogan: No Pitches | Only Passion
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# head tag info for the site

# ticket info
tickets: https://wichitalks.eventbrite.com

# Social Media and Contact info
social:
facebook: wichitalks
github: wichitalks
instagram: wichitalks
linkedin: 22333834
twitter: wichitalks
email: info@wichitalks.com

# Build settings
markdown: kramdown

# Collections
collections:
  - blog